### ISSUE TITLE
Optional HTTP verb

### ISSUE THREAD

**Issue by lcptrs** [alisa101rs/dothttp#4]
**Describe the bug**
Trying to run a request without a HTTP verb results in an error.

**To Reproduce**
1. This script file content `http://pokeapi.co/api/v2`
2. See error
```
Error: Failed parsing file: "tests/sample.http"

Caused by:
     --> 1:1
      |
    1 | http://pokeapi.co/api/v2
      | ^---
      |
      = expected file
```

**Expected behavior**
`GET` should be the fallback or default verb and thus a GET request with the provided url should be issued.

**Additional context**
I'm already working on a PR to achieve this: https://github.com/lcptrs/dothttp/tree/optional-method

**Comment by lcptrs** [comment]
off topic:
I've stumbled upon this on my search of an open source, text based http client. Only after this I found the HttpClient of Intellij and was at least a bit happy to have a tool that has the features I need.
So seeing, that someone wants to revive an open source alternative for this makes me happy! I'd like to contribute here, but my Rust & OSS knowledge is only theoretical up to this point. So please, bare with me while I'm doing my baby steps! :)

**Comment by alisa101rs** [comment]
Thank you for your bug report and for your kind words! 
No worries, I will help you to review your PR :)

**Comment by lcptrs** [comment]
Another small suggestion: What do you think of an `ijhttp compatibility` label?
