### ISSUE TITLE
Allow line-breaks inside the url

### ISSUE THREAD

**Issue by lcptrs** [alisa101rs/dothttp#7]
**Describe the bug**
If a url contains line-breaks, the values of the following lines will be ignored and thus a wrong url will be executed.

**To Reproduce**
1. This script file
```
GET https://pokeapi.co/api/v2/pokemon
  ?offset=20
  &limit=20
```
2. Resulting request:
```
[sample.http / #1]
GET https://pokeapi.co/api/v2/pokemon

HTTP/2 200 OK
```

**Expected behavior**
The whole request should be issued: `GET https://pokeapi.co/api/v2/pokemon?offset=20&limit=20`

**Additional context**
It must be only considered part of the url, if the next part in the new line has at least one leading whitespace.

**Comment by alisa101rs** [comment]
closed by #10
